### ISSUE TITLE
core-1.4.1-beta

### ISSUE THREAD

**Issue by zzvv** [bladejava/postapi#1]
貌似中央只有alpha 版本无beta 版

**Comment by biezhi** [comment]
已经release。 maven有点慢:joy:

**Comment by zzvv** [comment]
考虑国内用户,很多开发者都用的oschina的maven ,建议考虑上传一份至oschina的maven镜像库中

王爵 <notifications@github.com>于2015年10月31日周六 下午9:08写道：

**Comment by biezhi** [comment]
好的~

**Comment by zzvv** [comment]
上传了吗,- - 代理不给力,坐等.哈哈

王爵 <notifications@github.com>于2015年10月31日周六 下午9:16写道：

**Comment by biezhi** [comment]
我传到oschina的maven库了

**Comment by zzvv** [comment]
速度杠杠的.

王爵 <notifications@github.com>于2015年10月31日周六 下午9:43写道：

**Comment by zzvv** [comment]
建议pom.xml 配置文件内嵌入jetty or tomcat 运行容器

tory zzcv <2pporg@gmail.com>于2015年10月31日周六 下午9:49写道：

**Comment by biezhi** [comment]
这个都可以的，你需要的话自行加入。因为这里做了使用main函数启动，IDE直接启动，命令行可参考 https://biezhi.me/article/177.html
